import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>David</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="">
				<h1
					className="text-9xl text-
         font-thin"
				>
					<a href="https://nextjs.org">Portafolio</a>
				</h1>
			</main>
		</div>
	);
}
